default: &default
  host: localhost
  username: guest
  password: guest
  port: 5672

development:
  <<: *default
  vhost: /apollo-crawler-development

test:
  <<: *default
  host: apollo-crawler.no-ip.org
  vhost: /apollo-crawler-test

production:
  <<: *default
  host: apollo-crawler.no-ip.org
  vhost: /apollo-crawler-production
